site_name: Pureth

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - pymdownx.superfences

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true

nav:
  - EIP-7745 Log index:
    - event-logs.md
