site_name: Pureth

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
  - mkdocs_matplotlib

nav:
  - index.md
  - Log reform:
    - event-logs.md
    - logs-bloom.md
    - log-value-index.md
