name: Update GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up MkDocs
        run: pip install -r requirements.txt

      - name: Deploy to Pages
        run: mkdocs gh-deploy --no-history
